### ISSUE TITLE
Can Mimi dimensions be Any?

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#138]
The `MetaVariable` and `MetaParameter` classes define their dimensions as `Array{Any}`.  First, why isn't that a vector?

Second, Model's `indices_counts` and `indices_values` dictionaries map from `Symbol` (which I always thought dimensions had to be).  So these will fail if the dimensions are anything but symbols.

Can we just define the dimensions field in variables and parameters as `Vector{Symbol}`?

I'm having type stability problems otherwise.

**Comment by ckingdon95** [comment]
They can be numbers. For example when someone defines a parameter in defcomp like: 

p = Parameter(index=[5])

This parameter (once the component is instantiated) is a five element array without any dimension names, and the dimension field in the MetaParameter is just [5].

But yes it could be Vector{Any} instead of an Array because it is always just a list.

To address type stability problems, I suppose we could type if as Union{Symbol, Number} or something like that? not sure if that will work properly.

**Comment by jrising** [comment]
Good point.  But in this case, the modeler doesn't care what the index labels are, but might still want `indices_values` to work.  I propose that we generate a list of symbols, like `symbol("ind$n")` and keep the underlying object as a dictionary of symbols.

**Comment by ckingdon95** [comment]
I believe in this case, this index does not show up in m.indices_values. It's sort of like this index only belongs to that parameter, and not to the indices the model knows about. So the model's indices_values is currently a dictionary of symbols.

But we do have to leave the MetaParameter's dimensions field typed as Vector{Any}. 

Basically, I'm not sure what can/should be changed for this.

**Comment by jrising** [comment]
Okay.  I don't have my code with me that was causing the problem, but I think it's reasonable for this to stay as `Any`.  I'm going to close this for now, but I might re-open it if I remember any other twists.
