### ISSUE TITLE
Combine scalar and non-scalar parameters

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#177]
Presently there are distinct classes storing scalar and non-scalar variables and parameters. If we represent scalars as a Vector of length 1 and an empty dimensions array, it would be easy to test for scalar variables/parameters (`length(dimensions) == 0`), and we can treat scalars vs non-scalars more uniformly. 

With this approach, we would, for example, simply call `ModelParameter(...)` or `ModelVariable(...)` without a dimensions argument to create a scalar parameter.

**Comment by davidanthoff** [comment]
So in the new dot overloading story I've used `Ref{T}` for scalars. I guess the question with using vectors of length 1 is how we would distinguish that from a true vector with length 1. We might not need to, I'm not sure about that right now, but there might be cases where we want to distinguish between a vector of length 1 and a scalar. Certainly they are handled differently in the ``run_timestep`` function: e.g. ``v.scalarvar = p.scalarparam`` vs. ``v.vecvar[1] = p.vecpar[1]``.

**Comment by rjplevin** [comment]
Presumably we would define a dimension for the "real" vector of length 1, so length(dimensions) == 0 would be the test for a scalar.

**Comment by davidanthoff** [comment]
I guess we would just have to make sure that we have access to that everywhere, which we might not. For example, in the generated function for the property get and set method, we don't. The methods in ``dotoverloading.jl`` really need to be able to distinguish those cases based on the type only, because we don't have access to anything else in the generated function.
