### ISSUE TITLE
Mimi should not require ExcelReaders

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#206]
Mimi.jl currently includes mcs/mcs.jl, which uses ExcelReaders.  There are a two things wrong with this:
1. REQUIRE does not include ExcelReaders.
2. Mimi, as a concept, should not require ExcelReaders.

I suggest checking in mcs.jl whether ExcelReaders is installed, and simply disabling that functionality, with a note if any of it is attempted to be used.

**Comment by rjplevin** [comment]
James - Thanks for catching this.

1. Agreed -- this was an oversight.

2. Can you explain why this is so?

It's not clear to me where the line should be drawn. Should the Mimi "concept" require DataFrames, Plots, Electron, JSON, or Distributions? Should these also be optional? In my view, functionality that is commonly required by Mimi models is reasonable to provide in Mimi, e.g., empirical distribution data stored in spreadsheets, or saving results in spreadsheets.

I wonder if the issue is that ExcelReaders wraps a Python module and triggers installation of too much stuff, or has other installation issues. If we switch to a lighter-weight package, would you still object? Taro.jl requires java, and XLSXReader.jl isn't very complete.

**Comment by jrising** [comment]
Hi Richard,

I don't think this is a particularly subjective issue, though I recognize that it's a subtle one.  The thing to do is to step back and identify the goals of Mimi, and then the minimum set of requirements necessary to perform that goal.  Julia's ambitious package management system just incentivizes a good programming practice of keeping packages targeted.

So, what goal of Mimi does having ExcelReaders serve?  I can imagine answers that completely justify its inclusion.

If, for example, it's to provide more ways to read data for initializing models, that's a slippery slope.  In that case, I think we would want to split reading options from Mimi's data structure.

**Comment by davidanthoff** [comment]
I think this situation will improve down the road: one issue we have right now is that our models are not packages, so they cannot specify packages that they require. So we have these manual installation instructions for say mimi-rice-2010 that say you need to install ExcelReaders.jl for it to work. The new package manager in julia 0.7 will allow us to specify requirements for a model, which will be nice.

I tend to agree that we shouldn't add ExcelReaders.jl specifically as a dependency. One reason is that it makes the whole installation more brittle by requiring a Python story, the other is that there are lots of use cases for Mimi.jl where this is really not needed, essentially we are only using this for the DICE/RICE family right now, I believe.

In general, for tabular data, we should just support my iterable tables interface if we need to be able to consume tabular data. At that point we have absolutely minimal dependencies, but things will work with almost any tabular source (DataFrame, lots of different file formats etc.).

**Comment by rjplevin** [comment]
I will revise this. I agree that more flexibility in package management is the answer. Python setuptools, for example, supports optional components, which would be a clean way to handle this sort of thing.

**Comment by rjplevin** [comment]
I've made the requested changes in the RP branch.

**Comment by jrising** [comment]
Great, thanks for doing this.
