### ISSUE TITLE
Can we remove Electron?

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#207]
Electron is failing to build on Travis, resulting in my tests not running:

![image](https://user-images.githubusercontent.com/579448/38668553-1161281a-3e3c-11e8-9018-3168f819747d.png)

Does Mimi need Electron?

**Comment by davidanthoff** [comment]
We added a UI piece to Mimi.jl that depends on Electron. So probably the better strategy would be to fix the build issues. Another option would be to move the UI piece into its own package, but it is so useful that it would be nicer to just keep it where it is.

@jrising are these travis runs on this repo here, or some other repo? Can you post a link to the travis log?

**Comment by jrising** [comment]
Actually, this was driven by a failure to ExcelReaders on travis, and the Electron error was a red herring.  I can see the point of having a light UI in Mimi, but I could easily imagine a really cool, feature-full UI, which then I think should be pulled out into another package, like OptiMimi is.

Anyway, It looks like Electron is not causing a problem.  Issue closed.

**Comment by rjplevin** [comment]
Just to be clear -- we don't consider the updated master branch of Mimi to be completely ready for prime time. We wanted to commit a large set of changes so that we could continue development in smaller increments. I updated almost all of Mimi's internal tests last week. Several of the models have been updated, but there still may be (smaller) changes to the API.
