### ISSUE TITLE
How to represent data in components that have different first/last times?

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#321]
As I'm migrating the code to 1.0, I'm encountering errors in tests that are sometimes unclear how to fix. Here's one...

We allow components to have a different first and last date than the dimension in question would suggest. So if `:time` is, say, 2010-2100, a component might start in, 2050. It's `run_timestep` won't be called for years 2010-2049.

Currently,  the component param/var allocates storage for the whole dimension, with the value for the variable's first year at index 1. The vector is padded with `NaN`s to the length of the dimension. I'm not sure how conscious a decision this was, but this is how it works now.

The `getdataframe` function handles it differently: values for the years supported by the component are returned, but these are padded before / after (along the time dimension) for any years that component excludes. 

Pictorally, where the parameter looks like this:
```
x x x x x x x x x x x NaN NaN NaN
^ first             ^last
```
a column in the dataframe might look like this:
```
NaN NaN x x x x x x x x x x x NaN
        ^ first             ^ last
```
It makes sense to use the latter format to store vars and params since this facilitates combining data across components with different first/last periods. I'm inclined to change the storage in components to work this way, but I wanted to get input from you guys first.

**Comment by lrennels** [comment]
I've actually been wondering about this one too, and had the same question about whether it was consciously done.  I think changing the storage in components to work like the latter makes a lot more sense.

**Comment by ckingdon95** [comment]
I think we should have the allocation make the parameter array the length of the dimension in the component, without the trailing NaNs. This would solve the tests that are failing in test_connectorcomp, and allow the same "fast indexing" that was the original intention (where the array and the index have the same `first` value). I'm happy to try this today and see what happens, if we think it's worthwhile to try

**Comment by ckingdon95** [comment]
I think it makes sens for `getdataframe` to display the full length array with NaN's, so there's no ambiguity about if you're looking at the model's time dimension or the component's time dimension, but what would we gain by having the internal storage do this as well? I think it's more clear (and potentially faster) if the internal storage only has an array for the needed length.

**Comment by rjplevin** [comment]
Actually, it should pad with `missing` values since `NaN` generally means an arithmetic operation failed, while what we really have is a "no data" situation.

**Comment by ckingdon95** [comment]
Hmm actually your solution wouldn't be causing more integer division, since every array would use the same index, so maybe it's not slower...

**Comment by lrennels** [comment]
Oh I was asking you both!

**Comment by ckingdon95** [comment]
labeled this as both an enhancement and a bug-- enhancement for making the storage arrays make more sense, but then bug because the connectorcomps aren't working

**Comment by ckingdon95** [comment]
to do:
- during `build`: allocate storage arrays to be the full length of the model's time dimension, and fill in `missing` values before and after the `first` and `last` values for the corresponding component
- during `run`: no longer need separate clocks for each component. use one clock, but still check that `gettime(clock)` is between the `first` and `last` values for the component before calling the `run_timestep` for that component
- will need to add methods to `is_first` and `is_last` functions used in the `run_timestep` to check against the component's `first` and `last` values (rather than just checking `ts.t==1` and `gettime(ts)==LAST`)

**Comment by ckingdon95** [comment]
@rjplevin do the above steps make sense? Or should we not simplify the clocks during run? this would prevent the user from using `ts.t` during `run_timestep` and expecting a component-specific index, but I think that might be for the best, since it would force the use of `gettime(ts)` so that it's explicit what year they are trying to check against

**Comment by rjplevin** [comment]
Yes, that's how I was thinking of it. All I would add is that we can eliminate some of the methods that exist only to handle disparate indices.

I didn't consider the clock simplification, but I like it! I'd say get it working first without addressing the clocks, if possible, and clean that up in a second PR.

**Comment by rjplevin** [comment]
For out-of-bounds values, I have `missing` crossed out in my meeting notes and `nothing` in its place. @davidanthoff, didn't we decide on `nothing` since `missing` suggests there _should_ be a value?

However, on reading [this](https://julialang.org/blog/2018/06/missing), it's not clear that we get the same benefit from `nothing`.

But either way it will be Union. See and https://julialang.org/blog/2018/08/union-splitting for interesting info.

**Comment by ckingdon95** [comment]
another question: do we want `getindex(mi, comp_name, datum_name)` to return the full array, or just the portion relevant to that component's time dimension?

**Comment by rjplevin** [comment]
Good question. Depending on use case, I could see either being appropriate. My initial take would be to return the full array, since this is simpler. However, this particular `getindex` is just a convenience for interactive mode rather than something used in the code. (At least I believe that's probably true, without having checked...) So I'm not sure. @davidanthoff should definitely weigh in.

**Comment by ckingdon95** [comment]
I think the `getindex` question also falls into the broader "user experience" planning we want to do soon... for example, should we offer the ability to index into the datum arrays by their dimension names, like:
```
gdp = m[:socioeconomics, :gdp]
gdp[2100, :USA]
```
which would require more design planning. So I agree that for now we should just return the whole array and revisit this later.

**Comment by rjplevin** [comment]
The `Dimension` type should already handle this.

**Comment by ckingdon95** [comment]
right, I was just imagining that we could support an even more user-friendly way of accessing values at some point, without needing to explicitly call Dimension. But it was just a hypothetical to say that we may later on change our mind about whether or not we return the whole array. 

Related, I just made the first change for storage length (using "missing" values for now, we can decide on that later) and this results in several of our own tests failing that expect the array returned by getindex to start at whatever the first value for the component is. 

I still think we should return the whole array, I just want to note that I now need to modify how the test files access the values. (And I think I can make the tests read better anyway like you mentioned on slack recently!)

**Comment by ckingdon95** [comment]
@rjplevin @davidanthoff I believe these are the things we listed today for me to do. Feel free to add/edit.

To do:
- Error if no backup data provided when needed
- add check for missing values during calls to getindex (indexing a timesteparray with a timestep)
- make `getdataframe` use `missing` instead of `NaN` for values outside of components' time spans
- need to use `missing` for unititialized scalars as well, and add same check when they are accessed before being computed
- eventually, reconsider visibility of ConnectorComp's and other internal components
