### ISSUE TITLE
Methods get overwritten

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#397]
I get this message
```
julia> using Mimi
[ Info: Recompiling stale cache file C:\Users\david\.julia\compiled\v1.0\Mimi\LtuND.ji for Mimi [e4e893b0-ee5e-52ea-8111-44b3bdec128c]
WARNING: Method definition run_mcs(Mimi.MonteCarloSimulation, Array{Mimi.Model, 1}) in module Mimi at C:\Users\david\.julia\dev\Mimi\src\mcs\montecarlo.jl:506 overwritten at C:\Users\david\.julia\dev\Mimi\src\mcs\montecarlo.jl:512.
WARNING: Method definition #run_mcs(Any, typeof(Mimi.run_mcs), Mimi.MonteCarloSimulation, Array{Mimi.Model, 1}) in module Mimi overwritten.
```
Something probably gets included twice somewhere. One of the benefits of having all include statements in one file ;)

**Comment by davidanthoff** [comment]
Oh, and just to clarify: I think we should get to a situation where the package is really "quiet" and doesn't show anything like that, nor any other diagnostic output that is of no interest to end users.

**Comment by rjplevin** [comment]
Actually, this wasn't an "include" issue -- there are several method signatures for `run_mcs` and there appears to be overlap. I'll fix it now...

**Comment by rjplevin** [comment]
@lrennels,  I believe you added some of the new `run_mcs` methods. I believe I corrected a couple of things (see upcoming PR) but I'm not clear about how some of these are to be used. Specifically, when calling `run_mcs` with a single model, the default `models_to_run` is incremented, but when calling it with a vector of models, there is no equivalen `models_to_run::Int=length(mcs.models) + length(models)`. So a vector of 1 would be handled differently than a single model. Is that intended?

It would be good to document these to describe the use case each is handling since it isn't obvious (to me, at least.) Thanks!
